### ISSUE TITLE
Templating fluent.conf

### ISSUE THREAD

**Issue by jnogol** [idealista/fluentd-role#2]
### Description

In `tasks/config.yml` there is a task that _copies_ `fluent.conf` from files. It would be interesting templating this file instead of copying, because we can then use this role to deploy fluentd to different hosts.

**Comment by jnogol** [comment]
Problem is that, using the role within a playbook, is not possible to override the role template. A workaround could be changing the template `src` to a variable, so it can be changed in the playbook and therefore there is no need to add a new task.

```yml
- name: FLUENTD | Copy server config
  template:
    src: "{{ fluentd_config_template }}"
```
In the role's `defaults/main.yml`:

```yml
fluentd_config_template: fluentd/fluent.conf
```

In the playbook:

```yml
fluentd_config_template: "{{ playbook_dir }}/templates/path/to/template"
```
What do you think, @jdvr @jmonterrubio @dortegau?
